// Session status feed — rewritten by Claude at every checkpoint.
window.SESSION_STATUS = {
  updated: "2026-08-02T05:20:00+01:00",
  phase: "Wind-down — four findings landed, all gated",
  headline: "The measurement can't support the claim we set out to make — and that's the stronger result. FA saturates (49%), more samples provably don't help, the detector's whole signal is 0.184 nats, and ~2/3 of the raw effect is selection-on-noise.",
  gpu: { job: "winner's-curse re-eval (running, checkpointed)", detail: "resume with the same command; replaces the n=10 retention figure with n=80" },
  tasks: [
    { name: "Ceiling finding: 49% of FA targets saturate at ln(10)", state: "done" },
    { name: "N=20 verdict: censoring is STRUCTURAL, test is degenerate", state: "done" },
    { name: "Dynamic range: d=0.28, 26% of clean correct in top decile", state: "done" },
    { name: "Winner's curse: only 32% retention on a fresh seed (n=10/80)", state: "done" },
    { name: "Identifiable FA headline: 39% [29,49] operating-point flips", state: "done" },
    { name: "Exact beta-binomial test + 4 triggered deviations logged", state: "done" },
    { name: "Finish winner's-curse run to n=80", state: "todo" },
    { name: "Finish hide cell 17->80 (uncensored; pre-commit its effect floor first)", state: "todo" },
    { name: "Quantify benign-paraphrase ceiling reach ('no attack required')", state: "todo" },
  ],
  log: [
    "22:15 — start; ablation + 3 agent teams launched, stop button armed",
    "23:20 — critic: K=180 judge run = 9.5 GPU-DAYS; 'feasible rate 1.000' shown to be",
    "         TRUE BY CONSTRUCTION (verified in source, withdrawn, real counters added)",
    "00:00 — EXACT beta-binomial test prices the search budget into the null",
    "00:25 — CEILING: 49% of FA targets saturate; fixed the tie bug it exposed",
    "01:15 — critic's catch: the ceiling KILLS the test. Confirmed degenerate, power 0.00",
    "03:20 — tightened MY OWN ambiguous pre-commitment BEFORE the data landed",
    "04:05 — N=20 VERDICT: headroom gain only +0.11 median -> do not proceed",
    "04:40 — verified N=20 draws are fresh before believing any replication claim",
    "05:10 — WINNER'S CURSE MEASURED: +0.811 -> +0.263 on a fresh seed (32% retention)",
    "05:20 — wind-down; everything committed, handoff rewritten",
  ],
};
