window.SESSION_STATUS = {
  updated: "2026-08-04T07:30:00+01:00",
  phase: "Day 1 — the blocker is cleared, definitive design pre-committed",
  headline: "The tie question is settled: randomized ties are calibrated AND powerful AT N=10 (0.84@2x, m=50). My 'ceiling kills it' verdict was wrong — it was the tie rule. The N=20 detour is cancelled and the definitive run is costed at ~67 GPU-h.",
  gpu: { job: "winner's-curse (56/80) -> hide cell (17->80)", detail: "~14h; hide picks up the new instrumentation automatically (fresh interpreter). Then FA re-run, then the definitive null control." },
  tasks: [
    { name: "Tie rule settled by simulation (randomized wins)", state: "done" },
    { name: "Instrumented optimiser to record tie multiplicity b", state: "done" },
    { name: "Randomized exceedance wired in as the CLAIM statistic + guard rail", state: "done" },
    { name: "Definitive design PRE-COMMITTED (N=10, m=50, ~67 GPU-h)", state: "done" },
    { name: "Flip test built, measured anti-conservative, QUARANTINED", state: "done" },
    { name: "winner's-curse to n=80 (GPU, running)", state: "doing" },
    { name: "hide cell 17->80 (GPU, queued behind it)", state: "doing" },
    { name: "FA re-run under instrumentation (tag _defb, ~13h)", state: "todo" },
    { name: "DEFINITIVE null control (~67h) — the headline experiment", state: "todo" },
    { name: "Fix overstated dynamic-range claims (C3/C4/C5)", state: "todo" },
  ],
  log: [
    "04:50 — session resumed; GPU chain launched immediately (long pole first)",
    "05:20 — derived P(benign>attack-max) under an atom; verified vs simulation",
    "05:40 — concluded (WRONGLY) that no max-based statistic could survive the ceiling",
    "06:10 — showdown: randomized ties give power 0.71@2x at FULL saturation. I was wrong;",
    "         the signal is the MULTIPLICITY at the max, not its value. b must be measured.",
    "06:30 — found b was UNRECORDABLE (optimiser filtered ties out before the gate). Fixed.",
    "07:00 — built a flip test, measured its H0 level at 0.35-0.81, quarantined it",
    "07:20 — power at real saturation: m=50 gives 0.84@2x. Pre-committed the design.",
  ],
};
